name: MissingCommands-OG
author: s0me0ne-coder
description: A plugin to say why a certain command doesn't exist
website: https://github.com/true-og/MissingCommands-OG/
version: 1.0
api-version: 1.18
main: plugin.MissingCommandsOG
commands:
   kit:
      description: Placeholder
      usage: /kit
      permission: missingcommandsog.canviewplaceholdercommands
   wild:
      description: Placeholder
      usage: /wild
      permission: missingcommandsog.canviewplaceholdercommands
   guild:
      description: Placeholder
      usage: /guild
      permission: missingcommandsog.canviewplaceholdercommands
   f:
      description: Placeholder
      usage: /f
      permission: missingcommandsog.canviewplaceholdercommands
   faction:
      description: Placeholder
      usage: /faction
      permission: missingcommandsog.canviewplaceholdercommands
   seed:
      description: Placeholder
      usage: /seed
      permission: missingcommandsog.canviewplaceholdercommands

